openapi: 3.0.0
info:
  title: MS-CREDENTIALS-CONTROL
  version: 1.0.0
  description: Microservicio para gestión de credenciales y generación de tokens JWT.

servers:
  - url: http://localhost:8080
    description: Entorno local

paths:
  /auth/token:
    post:
      summary: Generar token de acceso
      description: Genera un token JWT basado en credenciales.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        200:
          description: Token generado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        401:
          description: Credenciales incorrectas
        500:
          description: Error interno del servidor

  /auth/validate:
    post:
      summary: Validar token
      description: Valida un token JWT para comprobar su autenticidad.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenValidationRequest'
      responses:
        200:
          description: Token válido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenValidationResponse'
        401:
          description: Token no válido o expirado
        500:
          description: Error interno del servidor
  /auth/register:
    post:
      summary: Registrar nuevas credenciales
      description: Registra nuevas credenciales en el microservicio.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequest'
      responses:
        201:
          description: Credenciales registradas con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        400:
          description: Solicitud incorrecta o credenciales duplicadas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        cluster_key:
          type: string
          description: Clave del cluster para identificar las credenciales.
        user:
          type: string
          description: Nombre de usuario para autenticación.
        password:
          type: string
          description: Contraseña para autenticación.
      required: [cluster_key, user, password]

    TokenResponse:
      type: object
      properties:
        token:
          type: string
          description: El token JWT generado.

    TokenValidationRequest:
      type: object
      properties:
        token:
          type: string
          description: El token a validar.
      required: [token]

    TokenValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: Indica si el token es válido.

    CredentialRequest:
      type: object
      properties:
        cluster_key:
          type: string
          description: Clave del cluster para identificar las credenciales.
        user:
          type: string
          description: Nombre de usuario.
        password:
          type: string
          description: Contraseña.
      required: [ cluster_key, user, password ]

    CredentialResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de confirmación o respuesta.


    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Mensaje de error para solicitudes incorrectas.